version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1

jobs:
  build:
    description: 'Run build'
    executor: node/default
    steps:
      - checkout
      - run:
          name: 'List files'
          command: 'ls -al'
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn-lock.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: 'yarn build'
  test:
    description: 'Build docker image'
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: Build
          command: 'docker build -t ecoach .'

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
