version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: Build
          command: 'docker build -t ecoach .'

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
