version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1
  deploy-to-heroku: rise/deploy-to-heroku@0.0.6

jobs:
  build_app:
    description: 'Run build'
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: 'yarn build'
  test:
    description: 'Test app'
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: 'yarn test'
  build_docker:
    description: 'Build docker image'
    executor: docker/machine
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: 'Install Heroku CLI, if necessary'
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Build
          command: 'docker build -t ecoach .'
      - deploy-to-heroku/install_dependencies
      # - run:
      #   name: Login into Heroku Docker Repository
      #   command: >
      #     docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY
      #     registry.heroku.com

workflows:
  build_and_test:
    jobs:
      - build_app
      - test:
          requires:
            - build_app
      - build_docker:
          requires:
            - test
            - build_app
          # filters:
          #   branches:
          #     only: master
