version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1
  heroku: circleci/heroku@1.0.1

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
  build:
    description: 'Run build'
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: 'yarn build'
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
  test:
    description: 'Test app'
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: 'yarn test'
  bdd:
    description: 'Run BDD'
    executor: node/default
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-repo-{{ .Branch }}-{{ .Revision }}
      - run:
          name: BDD
          command: 'yarn bdd'

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
