version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.0.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - docker/publish:
        deploy: false
        image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
